//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FL_ACME
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_AZKAR
    {
        public int Azkar_ID { get; set; }
        public string Azkar_Name { get; set; }
        public string Azkar_Arabic { get; set; }
        public string Azkar_Eng { get; set; }
        public string Azkar_Urdu { get; set; }
        public int Azkar_Count { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
