//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FL_ACME
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_ARTICLE
    {
        public int Aritcle_ID { get; set; }
        public string Article_Title { get; set; }
        public string Article_Descr { get; set; }
        public string Article_Notes { get; set; }
        public string Article_KeyPoints { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
