//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FL_ACME
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_EVENTS
    {
        public int Event_Id { get; set; }
        public string Event_Name { get; set; }
        public Nullable<System.DateTime> Event_Date_Eng { get; set; }
        public Nullable<System.DateTime> Event_Date_Urdu { get; set; }
        public string Event_Location { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string ImagePath { get; set; }
    }
}
