//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FL_ACME
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_NAMAZ
    {
        public int Namaz_ID { get; set; }
        public Nullable<int> Masjid_Id { get; set; }
        public Nullable<System.TimeSpan> Fajar_Time { get; set; }
        public Nullable<System.TimeSpan> Zuhar_Time { get; set; }
        public Nullable<System.TimeSpan> Asar_Time { get; set; }
        public Nullable<System.TimeSpan> Maghrib_Time { get; set; }
        public Nullable<System.TimeSpan> Isha_Time { get; set; }
        public Nullable<System.TimeSpan> Custom_Time { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
