//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FL_ACME
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_PROJECT
    {
        public int Project_ID { get; set; }
        public string Project_Title { get; set; }
        public Nullable<System.DateTime> Project_Date { get; set; }
        public string Project_Details { get; set; }
        public string Project_FB_Link { get; set; }
        public string Project_Insta_Link { get; set; }
        public string Project_YT_Link { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
