//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FL_ACME
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_Project_Images
    {
        public int Image_ID { get; set; }
        public Nullable<int> Project_ID { get; set; }
        public string ImagePAth { get; set; }
    }
}
