//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FL_ACME
{
    using System;
    using System.Collections.Generic;
    
    public partial class FL_SpecialDate
    {
        public int S_ID { get; set; }
        public string Event_Name { get; set; }
        public Nullable<System.DateTime> English_date { get; set; }
        public string Urdu_Date { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
